version: "3.3"
volumes:
  cba-postg-vol:
services:
  cba-postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - cba-postg-vol:/var/lib/postgresql/data
    ports:
      - 8893:5432
  cba-api:
    image: ghcr.io/calico-crusade/cardboardbox-anime/api:latest
    restart: always
    environment:
      - Mongo:ConnectionString=${MONGO_CON_URL}
      - Postgres:ConnectionString=User ID=${POSTGRES_USER};Password=${POSTGRES_PASS};Host=cba-postgres;Database=${POSTGRES_HOST};
      - OAuth:AppId=${OAUTH_APP_ID}
      - OAuth:Secret=${OAUTH_SECRET}
      - OAuth:Key=${OAUTH_KEY}
      - Ai:Url=${DISCORD_AI_URL}
      - Discord:PublicKey=${DISCORD_KEY}
      - Discord:AppId=${DISCORD_APPID}
      - Discord:Token=${DISCORD_TOKEN}
      - Match:Url=${MATCH_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8891:80
    depends_on:
      - cba-postgres
    volumes:
      - ./creds.json:/app/creds.json
      - ./image-cache:/app/wwwroot/image-cache
  cba-bot:
    image: ghcr.io/calico-crusade/cardboardbox-anime/bot:latest
    restart: always
    environment:
      - Discord:PublicKey=${DISCORD_KEY}
      - Discord:AppId=${DISCORD_APPID}
      - Discord:Token=${DISCORD_TOKEN}
      - Ai:Url=${DISCORD_AI_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - Match:Url=${MATCH_URL}
    depends_on:
      - cba-api
    volumes:
      - ./creds.json:/app/creds.json
      - ./persist:/app/persist
  cba-proxy:
    image: ghcr.io/calico-crusade/cardboardbox-proxy/api:latest
    restart: always
    environment:
      - Postgres:ConnectionString=User ID=${POSTGRES_USER};Password=${POSTGRES_PASS};Host=cba-postgres;Database=caching;
    ports:
      - 8899:80
    depends_on:
      - cba-postgres
    volumes:
      - ./file-cache:/app/file-cache
  cba-web:
    image: ghcr.io/calico-crusade/cardboardbox-anime/web:latest
    restart: always
    environment:
      - Mongo:ConnectionString=${MONGO_CON_URL}
      - Postgres:ConnectionString=User ID=${POSTGRES_USER};Password=${POSTGRES_PASS};Host=cba-postgres;Database=${POSTGRES_HOST};
      - OAuth:AppId=${OAUTH_APP_ID}
      - OAuth:Secret=${OAUTH_SECRET}
      - OAuth:Key=${OAUTH_KEY}
      - Ai:Url=${DISCORD_AI_URL}
      - Match:Url=${MATCH_URL}
    ports:
      - 8897:80
    depends_on:
      - cba-api
  cba-background:
    image: ghcr.io/calico-crusade/cardboardbox-anime/background:latest
    restart: always
    environment:
      - Mongo:ConnectionString=${MONGO_CON_URL}
      - Postgres:ConnectionString=User ID=${POSTGRES_USER};Password=${POSTGRES_PASS};Host=cba-postgres;Database=${POSTGRES_HOST};
      - OAuth:AppId=${OAUTH_APP_ID}
      - OAuth:Secret=${OAUTH_SECRET}
      - OAuth:Key=${OAUTH_KEY}
      - Ai:Url=${DISCORD_AI_URL}
      - Match:Url=${MATCH_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./creds.json:/app/creds.json
      - ./persist:/app/persist
    depends_on:
      - cba-api